apiVersion: v1
kind: ConfigMap
metadata:
  name: django-backend-config
  namespace: backend
  labels:
    app.kubernetes.io/name: django-backend
    app.kubernetes.io/component: backend
data:
  DJANGO_SETTINGS_MODULE: "core.config.settings.production"
  SERVICE_NAME: "django-backend"
  SERVICE_VERSION: "1.0.0"
  LOG_LEVEL: "INFO"
  DJANGO_DEBUG: "False"
