apiVersion: v1
kind: Service
metadata:
  name: django-backend
  namespace: backend
  labels:
    app.kubernetes.io/name: django-backend
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: django-backend
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
