# Generated by Django 5.2.17 on 2026-09-17 14:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiales', '0001_initial'),
        ('proveedores', '0001_initial'),
        ('sedes', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_reserva', models.CharField(max_length=20, unique=True, verbose_name='Código de Reserva')),
                ('fecha_cita', models.DateField(verbose_name='Fecha de la Cita')),
                ('hora_inicio', models.TimeField(verbose_name='Hora Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora Fin')),
                ('duracion_estimada_minutos', models.IntegerField(default=15, verbose_name='Duración Total (Min)')),
                ('estado', models.CharField(choices=[('RESERVADA', 'Reservada / Pendiente Confirmar'), ('CONFIRMADA', 'Confirmada'), ('EN_MUELLE', 'En Muelle / Descargando'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('RECHAZADA', 'Rechazada por Inconsistencia')], default='RESERVADA', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='vehiculos.conductor')),
                ('muelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='sedes.muelle')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='proveedores.proveedor')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'Citas',
                'ordering': ['-fecha_cita', '-hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCitaMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_estibas', models.IntegerField(default=1, verbose_name='Cantidad de Estibas')),
                ('tiempo_calculado_minutos', models.IntegerField(verbose_name='Tiempo Calculado (Min)')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='citas.cita')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_cita', to='materiales.material')),
            ],
            options={
                'verbose_name': 'Detalle de Cita',
                'verbose_name_plural': 'Detalles de Cita',
                'db_table': 'DetallesCitaMaterial',
            },
        ),
    ]
