# Generated by Django 5.2.17 on 2026-09-17 14:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT / RUT')),
                ('razon_social', models.CharField(max_length=150, verbose_name='Razón Social')),
                ('nombre_contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_contacto', models.EmailField(max_length=254, verbose_name='Correo de Contacto')),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'Proveedores',
            },
        ),
    ]
