# Generated by Django 5.2.17 on 2026-09-16 18:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(db_index=True, help_text='Verb describing the event, e.g. CREATE, UPDATE, DELETE, LOGIN.', max_length=100)),
                ('resource_type', models.CharField(db_index=True, help_text="Class / entity name of the affected resource, e.g. 'User', 'Order'.", max_length=100)),
                ('resource_id', models.CharField(blank=True, help_text="String representation of the affected resource's primary key.", max_length=255, null=True)),
                ('changes', models.JSONField(blank=True, help_text="Dictionary with 'before' and 'after' snapshots of changed fields.", null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('correlation_id', models.UUIDField(blank=True, help_text='Distributed tracing ID propagated via X-Correlation-ID header.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'created_at'], name='audit_user_created_idx'), models.Index(fields=['action', 'resource_type'], name='audit_action_resource_idx'), models.Index(fields=['created_at'], name='audit_created_idx')],
            },
        ),
    ]
