"""
Email service abstraction.

``EmailService`` wraps Django's email backend so the rest of the application
never imports ``django.core.mail`` directly.  The active backend is controlled
by ``settings.EMAIL_BACKEND``, making it straightforward to swap between
console, SMTP, and third-party providers without changing call-sites.

Usage::

    from infrastructure.email.backends import EmailService

    sent = EmailService.send_email(
        to=["user@example.com"],
        subject="Welcome",
        body="Thanks for signing up.",
    )
"""

from __future__ import annotations

import logging
from typing import Any

__all__ = ["EmailService"]

logger = logging.getLogger(__name__)


class EmailService:
    """Stateless email helpers that delegate to Django's email infrastructure."""

    @staticmethod
    def send_email(
        to: list[str],
        subject: str,
        body: str,
        html_body: str | None = None,
        from_email: str | None = None,
    ) -> bool:
        """Send a plain-text (and optionally HTML) email.

        Args:
            to:         List of recipient email addresses.
            subject:    Email subject line.
            body:       Plain-text message body.
            html_body:  Optional HTML alternative body.
            from_email: Sender address.  Falls back to ``settings.DEFAULT_FROM_EMAIL``.

        Returns:
            ``True`` if the email was accepted by the backend, ``False`` on error.
        """
        from django.core.mail import EmailMultiAlternatives

        try:
            msg = EmailMultiAlternatives(
                subject=subject,
                body=body,
                from_email=from_email,
                to=to,
            )
            if html_body:
                msg.attach_alternative(html_body, "text/html")
            msg.send()
            logger.info("Email sent to %s — subject: %r", to, subject)
            return True
        except Exception:
            logger.exception("Failed to send email to %s — subject: %r", to, subject)
            return False

    @staticmethod
    def send_template_email(
        to: list[str],
        template_name: str,
        context: dict[str, Any],
        subject: str,
        from_email: str | None = None,
    ) -> bool:
        """Render a Django template and send it as an HTML email.

        The template should produce the full HTML body.  A plain-text
        fallback is automatically generated by stripping HTML tags.

        Args:
            to:            List of recipient email addresses.
            template_name: Django template path, e.g. ``'emails/welcome.html'``.
            context:       Template context dictionary.
            subject:       Email subject line.
            from_email:    Sender address.  Falls back to ``settings.DEFAULT_FROM_EMAIL``.

        Returns:
            ``True`` if the email was accepted by the backend, ``False`` on error.
        """
        import re

        from django.template.loader import render_to_string

        try:
            html_body: str = render_to_string(template_name, context)
            # Strip HTML tags to create a plain-text fallback.
            plain_body: str = re.sub(r"<[^>]+>", "", html_body).strip()

            return EmailService.send_email(
                to=to,
                subject=subject,
                body=plain_body,
                html_body=html_body,
                from_email=from_email,
            )
        except Exception:
            logger.exception(
                "Failed to render/send template email — template: %r, to: %s",
                template_name,
                to,
            )
            return False
