# Generated by Django 5.2.17 on 2026-09-17 13:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Muelle',
            fields=[
                ('muelle_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_muelle', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
                ('tiempo_operacion', models.IntegerField(help_text='Tiempo en minutos')),
            ],
            options={
                'db_table': 'Muelles',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('sede_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_sede', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=50)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Sedes',
            },
        ),
        migrations.CreateModel(
            name='HabilitacionMuelle',
            fields=[
                ('habilitacion_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario_modificacion', models.ForeignKey(db_column='usuario_modificacion', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('muelle', models.ForeignKey(db_column='muelle_id', on_delete=django.db.models.deletion.CASCADE, related_name='habilitaciones', to='sedes.muelle')),
            ],
            options={
                'db_table': 'Habilitacion_Muelles',
            },
        ),
        migrations.AddField(
            model_name='muelle',
            name='sede',
            field=models.ForeignKey(db_column='sede_id', on_delete=django.db.models.deletion.CASCADE, related_name='muelles', to='sedes.sede'),
        ),
    ]
