# Generated by Django 5.2.17 on 2026-09-17 14:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código Tipo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Tipo')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Material',
                'verbose_name_plural': 'Tipos de Material',
                'db_table': 'TiposMaterial',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código Material / SAP')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Material')),
                ('tiempo_descarga_min_estiba', models.IntegerField(default=5, verbose_name='Minutos por Estiba')),
                ('activo', models.BooleanField(default=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='materiales.tipomaterial')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'db_table': 'Materiales',
            },
        ),
    ]
