# Generated by Django 5.2.17 on 2026-09-17 14:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula / Documento')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductores', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'db_table': 'Conductores',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa del Vehículo')),
                ('tipo_vehiculo', models.CharField(choices=[('TURBO', 'Turbo / Camión Pequeño'), ('SENCILO', 'Camión Sencillo'), ('TRAILER', 'Tractomula / Tráiler'), ('FURGON', 'Furgón')], default='TURBO', max_length=20)),
                ('vencimiento_soat', models.DateField(verbose_name='Vencimiento SOAT')),
                ('vencimiento_tecnomecanica', models.DateField(verbose_name='Vencimiento Tecnomecánica')),
                ('activo', models.BooleanField(default=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'Vehiculos',
            },
        ),
    ]
